### ISSUE TITLE
transform solved path  to  EWSN (for east/west/south/north) that the Mazebot expects 

### ISSUE THREAD

**Issue by mamonu** [mamonu/Astar#12]
So... the algorithm outputs this:
```md
[(0, 0), (1, 1), (2, 1), (3, 2), (4, 2), (5, 2), (6, 3), (7, 4), (8, 5), (9, 5),
(10, 5), (11, 5), (12, 4), (13, 3), (14, 2), (15, 1), (16, 1), (17, 1), 
(18, 2), (18, 3), (18, 4), (18, 5), (18, 6),(18, 7), (18, 8), (18, 9),
(18, 10), (18, 11), (18, 12), (19, 13), (19, 14), (19, 15),
(19, 16), (19, 17), (19, 18), (19, 19)] 

```

Mazebot wants 

```md

ENEESWWWSSSN 

```

what we need is a function that transforms the former to later.

ps. the output above has diagonal steps which the bot probably doesnt accept.
the algorithm has a way of disabling these..so the transforming function only needs to take care of  N / S / E / W

**Comment by scavenger29** [comment]
I am taking this up

**Comment by scavenger29** [comment]
Could you help me with the sense of direction? Like which way is North pointing to? Is it the right-hand side? Also, when the bot goes from (0,0) to (1,1), do we have to add two directions for it like N and E?

**Comment by mamonu** [comment]
Sure

north points up
west to the left
east to the right
 

just make it in a way that for example  

(0,0) to (0,1) is E
(5,5) to (4,5) is N

etc


So when its diagonal for the time.. either ignore it ! 
(or create 2 steps.your choice. Preferable to do 2 steps.)

As i said its easy to setup the algorithm to not allow diagonals 
its just that on the example that we run it does allow them.

**Comment by scavenger29** [comment]
The given sample output `ENEESWWWSSSN `  corresponds to the given input or is it just a format for the output? Because in the second step it is going from (1,1) to (2,1), which according to the directions should be South.

**Comment by mamonu** [comment]
its just the format of the output. Sorry for being unlclear on that !

**Comment by scavenger29** [comment]
Okay. Thanks!

**Comment by scavenger29** [comment]
https://github.com/mamonu/Astar/pull/13
I have created the PR with the required changes.

**Comment by mamonu** [comment]
accepted! good work . thanks
