### ISSUE TITLE
Follow coding best practices

### ISSUE THREAD

**Issue by mamonu** [mamonu/Astar#7]
Code works up to a point
But also its a mess.
Certain parts need to be in functions and it needs some TLC
This would be a great first issue for someone.
Make it pretty and readable and useful please

some guidance on how to do this can be found below:

https://docs.python-guide.org/writing/style/

**Comment by hangmansROP** [comment]
I'm happy to try and tidy this up for you :) I'm not sure about moving stuff into functions but I can work on the readability

**Comment by mamonu** [comment]
Hi.There was a pull request for another issue that got merged. As a result the code has changed. If you want to sync to those changes have a look at:

https://help.github.com/en/articles/merging-an-upstream-repository-into-your-fork

**Comment by hangmansROP** [comment]
Given it a shot in PR #10.

Let me know your thoughts!
